# Generated by Django 4.1.5 on 2023-03-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tittle',
            new_name='title',
        ),
    ]
